### ISSUE TITLE
Library doesn't work for current version of Nerves "1.5.0" with RPI3.

### ISSUE THREAD

**Issue by latachz** [arjan/nerves_io_rc522#1]
When I add library and use mix firmware there is a problem.

`** (Mix) Nerves encountered an error. %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: true}`

**Comment by arjan** [comment]
Strange. Is there more log output that might be relevant?

**Comment by latachz** [comment]
It started working after computer restart. Sorry for the problem.
